method: local_CRF
dataset:
    path: ./data/PTD/cap_visual_dataset.pkl
st_rerank: 
  enable: False
rerank:
  enable: True
  k1: 1
  k2: 1
  lambda: 0.8
adj2path: rnmf
dim: 2048
spatiotemporal:
    modelroot: ./model/PTD/
    locationroot: ./data/PTD/location.json
    name: super_MLP
cluster_threshold: 0.46
crf:
    alpha: 1
    u: 0
    T: 1
    nc_threshold: 0
    u1: 0.6
    u2: 0.19
    threshold: 0.93
  


  