method: local_CRF
dataset:
    path: ./data/PTD/pcb_visual_dataset.pkl
st_rerank: 
  enable: False
rerank:
  enable: True
  k1: 7
  k2: 2
  lambda: 0.9
adj2path: rnmf
dim: 12288
spatiotemporal:
    modelroot: ./model/PTD/
    locationroot: ./data/PTD/location.json
    name: super_MLP
cluster_threshold: 0.32
crf:
    alpha: 0.6
    u: 0.1
    T: 1
    nc_threshold: 0
    u1: 1.9
    u2: 0.08
    threshold: 0.9
  


  