method: local_CRF
dataset:
    path: ./data/PTD/mgn_visual_dataset.pkl
st_rerank: 
  enable: False
rerank:
  enable: False
  k1: 1
  k2: 2
  lambda: 0.8
adj2path: rnmf
dim: 2048
spatiotemporal:
    modelroot: ./model/PTD/
    locationroot: ./data/PTD/location.json
    name: super_MLP
cluster_threshold: 0.22
crf:
    alpha: 0.42
    u: 0.1
    T: 1
    nc_threshold: 0
    u1: 1.2
    u2: 1.7
    threshold: 0.9
  


  